Overload runSpec constructor to allow java list
mesosphere/usi pull request #76
Opened 2019-03-19 04:21 UTC by kvish

2019-03-19 07:51 UTC, alenkacz requested changes
I am requesting changes just so we can have the discussion around what way do we want to go with java apis. Ultimately it's a bit up to you guys but I would prefer to have them separated so java consumers are not concerned with java APIs

2019-03-19 07:51 UTC, alenkacz commented on core-models/src/main/scala/com/mesosphere/usi/core/models/RunSpec.scala
> +  def this(
I'll repost my comment on slack:

shouldn't we do all the java APIs in a separate namespace and ideally write them in java? Then we know they are java friendly :slightly_smiling_face: Akka has two namespaces as well and the ones for java are written in ... wait for it... Java :slightly_smiling_face:

2019-03-25 16:49 UTC, jeschkies commented
What do you think about using the builder pattern?

2019-03-25 22:17 UTC, kvish commented
ya @jeschkies that makes sense, we can just have a builder here that takes both args

2019-04-11 15:26 UTC, timcharper requested changes
Let's go the builder pattern for the Java interface

2019-04-20 23:09 UTC, closed without merging